### ISSUE TITLE
Change context menu when comments are present on a highlight

### ISSUE THREAD

**Issue by Sleuth56** [DanilaFe/matrix-highlight#13]
When a comment is on a highlight it should open the comment when clicking instead of a context menu that requires an other click to open that same menu. Also it would be nice to have the color buttons so you can change the highlight color without losing the comments.
![Screenshot_20211215_215534](https://user-images.githubusercontent.com/34520077/146299716-74b5b9a6-a2c2-4c74-87bc-3798b98ff157.png)
![Screenshot_20211215_215611](https://user-images.githubusercontent.com/34520077/146300325-71b5e339-ea11-4dc6-a256-12be76d4bcce.png)

**Comment by DanilaFe** [comment]
Since the context menu has been changed, I'm closing this in favor of #14.
