### ISSUE TITLE
Leave comments and comment threads

### ISSUE THREAD

**Issue by DanilaFe** [DanilaFe/matrix-highlight#3]
We want a Google Docs-like comment feature. We can use the Matrix Threads MSC for this.

**Comment by frandavid100** [comment]
Would it be possible to leave a root comment when highlighting some text? Or do comments always have to go in other messages of the thread?

**Comment by DanilaFe** [comment]
It seems like highlights can be root comments of threads. This feature is now in, so I'm closing the issue :)
